export interface Product {
    id: string;
    name: string;
    nameUz?: string;
    nameRu?: string;
    price: number;
    oldPrice?: number;
    image: string;
    category: string;
    rating: number;
    isNew?: boolean;
    description?: string;
    descriptionUz?: string;
    descriptionRu?: string;
    specs?: { [key: string]: string };
}

export interface News {
    id: string;
    title: string;
    excerpt: string;
    date: string;
    image: string;
    badge?: string;
    badgeColor?: string;
}

export interface Category {
    id: string;
    name: string;
    nameUz?: string;
    nameRu?: string;
    image: string;
    slug: string;
}

export const categories: Category[] = [
    { id: '1', name: 'Baby Diapers', nameUz: 'Bolalar tagliklari', nameRu: 'Детские подгузники', image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=400', slug: 'baby-diapers' },
    { id: '2', name: 'Drinks', nameUz: 'Ichimliklar', nameRu: 'Напитки', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400', slug: 'drinks' },
    { id: '3', name: 'Bread Products', nameUz: 'Non mahsulotlari', nameRu: 'Хлебные изделия', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400', slug: 'bread' },
    { id: '4', name: 'Grains', nameUz: 'Donli mahsulotlar', nameRu: 'Крупы', image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400', slug: 'grains' },
    { id: '5', name: 'Vegetables', nameUz: 'Sabzavotlar', nameRu: 'Овощи', image: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&q=80&w=400', slug: 'vegetables' },
    { id: '6', name: 'Fruits', nameUz: 'Mevalar', nameRu: 'Фрукты', image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=400', slug: 'fruits' },
];

export const products: Product[] = [
    // Baby Diapers
    { id: 'bd1', name: 'Pampers Premium Care 1', nameUz: 'Pampers Premium Care 1', nameRu: 'Pampers Premium Care 1', price: 180000, oldPrice: 200000, image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.9, isNew: true, description: 'Softest comfort and best skin protection from Pampers. 5-star skin protection.', descriptionUz: 'Pampersdan eng yumshoq qulaylik va eng yaxshi teri himoyasi. 5 yulduzli himoya.', descriptionRu: 'Мягчайший комфорт и лучшая защита кожи от Pampers. 5-звездочная защита.', specs: { 'Size': '1 (Newborn)', 'Count': '80 pcs', 'Origin': 'Poland' } },
    { id: 'bd2', name: 'Huggies Elite Soft 2', nameUz: 'Huggies Elite Soft 2', nameRu: 'Huggies Elite Soft 2', price: 195000, image: 'https://images.unsplash.com/photo-1558230559-679ce681ff57?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.8, description: 'Contains 100% organic cotton. Hypoallergenic and breathable.', descriptionUz: '100% organik paxtadan tayyorlangan. Gipoallergen va havo o\'tkazuvchan.', descriptionRu: 'Содержит 100% органический хлопок. Гипоаллергенные и дышащие.', specs: { 'Size': '2 (3-6kg)', 'Count': '66 pcs', 'Origin': 'Russia' } },
    { id: 'bd3', name: 'Meries Baby Diapers S', nameUz: 'Meries Bolalar Tagliklari S', nameRu: 'Meries Детские подгузники S', price: 210000, oldPrice: 230000, image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.7, description: 'Premium Japanese quality diapers with exceptional breathability.', descriptionUz: 'Ajoyib havo o\'tkazuvchanligi bilan premium yapon sifati.', descriptionRu: 'Японское премиум качество с исключительной воздухопроницаемостью.', specs: { 'Size': 'S (4-8kg)', 'Count': '82 pcs', 'Origin': 'Japan' } },
    { id: 'bd4', name: 'Pampers Pants 4', nameUz: 'Pampers Pants 4', nameRu: 'Pampers трусики 4', price: 160000, image: 'https://images.unsplash.com/photo-1563205856-4c7403567793?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.6, description: 'Easy on, easy off pants. 360 fit for active babies.', descriptionUz: 'Kiyish va yechish oson. Faol bolalar uchun 360 daraja moslik.', descriptionRu: 'Легко надевать и снимать. Посадка 360 для активных малышей.', specs: { 'Size': '4 (9-15kg)', 'Count': '52 pcs', 'Origin': 'Turkey' } },
    { id: 'bd5', name: 'Libero Comfort 3', nameUz: 'Libero Comfort 3', nameRu: 'Libero Comfort 3', price: 155000, image: 'https://images.unsplash.com/photo-1562947157-558256e25d40?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.5, description: 'Dermatologically tested. Lotion free.', descriptionUz: 'Dermatologik sinovdan o\'tgan. Losyonsiz.', descriptionRu: 'Дерматологически протестировано. Без лосьона.', specs: { 'Size': '3 (5-9kg)', 'Count': '60 pcs', 'Origin': 'Sweden' } },
    { id: 'bd6', name: 'Eco-Friendly Diapers', nameUz: 'Ekologik toza tagliklar', nameRu: 'Экологичные подгузники', price: 250000, image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 5.0, isNew: true, description: 'Biodegradable bamboo diapers. Gentle on skin and planet.', descriptionUz: 'Biologik parchalanadigan bambuk tagliklari. Teri va tabiat uchun xavfsiz.', descriptionRu: 'Биоразлагаемые бамбуковые подгузники. Безопасны для кожи и планеты.', specs: { 'Size': 'M', 'Count': '40 pcs', 'Material': 'Bamboo' } },
    { id: 'bd7', name: 'Night Time Diapers', nameUz: 'Tungi tagliklar', nameRu: 'Ночные подгузники', price: 190000, image: 'https://images.unsplash.com/photo-1549488827-0cfd695b2140?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.8, description: 'Extra absorbency for up to 12 hours of dry sleep.', descriptionUz: '12 soatgacha quruq uyqu uchun qo\'shimcha so\'riluvchanlik.', descriptionRu: 'Экстра впитываемость для 12 часов сухого сна.', specs: { 'Size': 'L', 'Count': '48 pcs', 'Type': 'Night' } },
    { id: 'bd8', name: 'Newborn Starter Pack', nameUz: 'Yangi tug\'ilganlar uchun to\'plam', nameRu: 'Набор для новорожденных', price: 120000, oldPrice: 140000, image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=600', category: 'Baby Diapers', rating: 4.9, description: 'Perfect starter kit for new parents. Includes wipes.', descriptionUz: 'Yangi ota-onalar uchun mukammal boshlang\'ich to\'plam. Salfetkalarni o\'z ichiga oladi.', descriptionRu: 'Идеальный стартовый набор. Включает салфетки.', specs: { 'Size': 'NB', 'Count': '30 pcs', 'Extras': 'Wipes' } },

    // Drinks
    { id: 'dr1', name: 'Coca-Cola 1.5L', nameUz: 'Coca-Cola 1.5L', nameRu: 'Coca-Cola 1.5Л', price: 12000, oldPrice: 14000, image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.8, description: 'Classic sparkling soft drink. Best served ice cold.', descriptionUz: 'Klassik gazli ichimlik. Muzdek holda ichish tavsiya qilinadi.', descriptionRu: 'Классический газированный напиток. Лучше всего пить охлажденным.', specs: { 'Volume': '1.5 L', 'Sugar': 'Yes', 'Origin': 'Uzbekistan' } },
    { id: 'dr2', name: 'Pepsi 1.5L', nameUz: 'Pepsi 1.5L', nameRu: 'Pepsi 1.5Л', price: 11500, image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.7, description: 'Bold, refreshing taste of Pepsi.', descriptionUz: 'Pepsi - dadil va tetiklashtiruvchi ta\'m.', descriptionRu: 'Смелый, освежающий вкус Pepsi.', specs: { 'Volume': '1.5 L', 'Sugar': 'Yes', 'Origin': 'Uzbekistan' } },
    { id: 'dr3', name: 'Fanta Orange 1.5L', nameUz: 'Fanta Apelsin 1.5L', nameRu: 'Fanta Апельсин 1.5Л', price: 12000, image: 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.6, description: 'Fruity orange taste. Made with fruit juice.', descriptionUz: 'Apelsin ta\'mi. Mevar sharbati qo\'shilgan.', descriptionRu: 'Апельсиновый вкус. С фруктовым соком.', specs: { 'Volume': '1.5 L', 'Flavor': 'Orange', 'Origin': 'Uzbekistan' } },
    { id: 'dr4', name: 'Natural Mineral Water', nameUz: 'Mineral Suv', nameRu: 'Минеральная Вода', price: 3000, image: 'https://images.unsplash.com/photo-1560023907-5f339617ea30?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.9, description: 'Pure mountain spring water.', descriptionUz: 'Sof tog\' buloq suvi.', descriptionRu: 'Чистая горная родниковая вода.', specs: { 'Volume': '0.5 L', 'Type': 'Still', 'Origin': 'Tian Shan' } },
    { id: 'dr5', name: 'Orange Juice 100%', nameUz: 'Apelsin Sharbati 100%', nameRu: 'Апельсиновый Сок 100%', price: 25000, oldPrice: 32000, image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.9, description: '100% natural orange juice without added sugar.', descriptionUz: 'Shakar qo\'shilmagan 100% tabiiy apelsin sharbati.', descriptionRu: '100% натуральный апельсиновый сок без сахара.', specs: { 'Volume': '1 L', 'Brand': 'Rich', 'Origin': 'Russia' } },
    { id: 'dr6', name: 'Apple Juice', nameUz: 'Olma Sharbati', nameRu: 'Яблочный Сок', price: 22000, image: 'https://images.unsplash.com/photo-1573500814966-2613ce91a5e1?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.7, description: 'Clarified apple nectar.', descriptionUz: 'Tiniqlashtirilgan olma nektari.', descriptionRu: 'Осветленный яблочный нектар.', specs: { 'Volume': '1 L', 'Brand': 'Bliss', 'Origin': 'Uzbekistan' } },
    { id: 'dr7', name: 'Red Bull Energy', nameUz: 'Red Bull Energy', nameRu: 'Red Bull Energy', price: 18000, image: 'https://images.unsplash.com/photo-1598460677112-25e40e4f8d4f?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.8, isNew: true, description: 'Vitalizes body and mind.', descriptionUz: 'Tana va ruhni tetiklashtiradi.', descriptionRu: 'Бодрит тело и дух.', specs: { 'Volume': '250 ml', 'Caffeine': 'Yes', 'Origin': 'Austria' } },
    { id: 'dr8', name: 'Iced Tea Lemon', nameUz: 'Limonli Sovuq Choy', nameRu: 'Холодный Чай Лимон', price: 9000, image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.5, description: 'Refreshing tea drink with lemon flavor.', descriptionUz: 'Limon ta\'mli tetiklashtiruvchi choy ichimligi.', descriptionRu: 'Освежающий чайный напиток со вкусом лимона.', specs: { 'Volume': '1 L', 'Brand': 'FuseTea', 'Flavor': 'Lemon' } },
    { id: 'dr9', name: 'Green Tea Bottle', nameUz: 'Ko\'k Choy', nameRu: 'Зеленый Чай', price: 7000, image: 'https://images.unsplash.com/photo-1627464082269-e91024bd3540?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.6, description: 'Cold brewed green tea without sugar.', descriptionUz: 'Shakarsiz sovuq damlangan ko\'k choy.', descriptionRu: 'Холодный зеленый чай без сахара.', specs: { 'Volume': '0.5 L', 'Sugar': 'No', 'Type': 'Green' } },
    { id: 'dr10', name: 'Cold Coffee Latte', nameUz: 'Sovuq Kofe Latte', nameRu: 'Холодный Кофе Латте', price: 15000, image: 'https://images.unsplash.com/photo-1579308104593-47055c57fba3?auto=format&fit=crop&q=80&w=600', category: 'Drinks', rating: 4.8, description: 'Ready to drink chilled latte.', descriptionUz: 'Ichishga tayyor sovutilgan latte.', descriptionRu: 'Готовый охлажденный латте.', specs: { 'Volume': '250 ml', 'Brand': 'Starbucks', 'Type': 'Latte' } },

    // Bread Products
    { id: 'br1', name: 'Non (Traditional Bread)', nameUz: 'Tandir Non', nameRu: 'Лепешка', price: 4000, image: 'https://images.unsplash.com/photo-1589139178465-950c44365859?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 5.0, description: 'Freshly baked traditional Uzbek flatbread.', descriptionUz: 'Yangi yopilgan an\'anaviy o\'zbek noni.', descriptionRu: 'Свежеиспеченная традиционная узбекская лепешка.', specs: { 'Weight': '400g', 'Type': 'Tandir', 'Origin': 'Local' } },
    { id: 'br2', name: 'Sliced White Bread', nameUz: 'Kesilgan Oq Non', nameRu: 'Нарезной Белый Хлеб', price: 6000, image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.5, description: 'Soft white bread, perfect for sandwiches.', descriptionUz: 'Yumshoq oq non, sendvichlar uchun mukammal.', descriptionRu: 'Мягкий белый хлеб, идеально для сэндвичей.', specs: { 'Weight': '500g', 'Sliced': 'Yes', 'Brand': 'Burs' } },
    { id: 'br3', name: 'Whole Wheat Bread', nameUz: 'Bug\'doyli Non', nameRu: 'Цельнозерновой Хлеб', price: 8000, oldPrice: 10000, image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.8, description: 'Healthy whole grain bread rich in fiber.', descriptionUz: 'Kletchatkaga boy foydali bug\'doy noni.', descriptionRu: 'Полезный цельнозерновой хлеб, богатый клетчаткой.', specs: { 'Weight': '400g', 'Grain': 'Whole Wheat', 'Dietary': 'High Fiber' } },
    { id: 'br4', name: 'Baguette', nameUz: 'Baget', nameRu: 'Багет', price: 5000, image: 'https://images.unsplash.com/photo-1595828859239-2fe49e7b233e?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.7, description: 'Crispy French style baguette.', descriptionUz: 'Qarsildoq fransuzcha baget.', descriptionRu: 'Хрустящий французский багет.', specs: { 'Weight': '250g', 'Style': 'French', 'Baking': 'Daily' } },
    { id: 'br5', name: 'Croissant Butter', nameUz: 'Saryog\'li Kruassan', nameRu: 'Круассан с Маслом', price: 12000, image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.9, isNew: true, description: 'Flaky, buttery croissants made with real butter.', descriptionUz: 'Haqiqiy saryog\'dan tayyorlangan qatlamli kruassanlar.', descriptionRu: 'Слоеная выпечка с настоящим сливочным маслом.', specs: { 'Pack': '2 pcs', 'Filling': 'None', 'Type': 'Butter' } },
    { id: 'br6', name: 'Rye Bread', nameUz: 'Javdar Noni', nameRu: 'Ржаной Хлеб', price: 9000, image: 'https://images.unsplash.com/photo-1533464731170-ae40417fc94e?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.6, description: 'Dense, dark rye bread with caraway seeds.', descriptionUz: 'Ziravorli to\'yimli qora javdar noni.', descriptionRu: 'Плотный, темный ржаной хлеб с тмином.', specs: { 'Weight': '450g', 'Grain': 'Rye', 'Style': 'Borodinsky' } },
    { id: 'br7', name: 'Burger Buns (4pcs)', nameUz: 'Burger nonlari (4 dona)', nameRu: 'Булочки для бургеров (4 шт)', price: 10000, image: 'https://images.unsplash.com/photo-1553185368-80f2dff171a8?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.5, description: 'Soft sesame topped buns for burgers.', descriptionUz: 'Burgerlar uchun kunjutli yumshoq nonlar.', descriptionRu: 'Мягкие булочки с кунжутом для бургеров.', specs: { 'Count': '4 pcs', 'Topping': 'Sesame', 'Use': 'Burgers' } },
    { id: 'br8', name: 'Garlic Bread', nameUz: 'Sarimsoqli Non', nameRu: 'Чесночный Хлеб', price: 8500, image: 'https://images.unsplash.com/photo-1573140247632-f84660f67627?auto=format&fit=crop&q=80&w=600', category: 'Bread Products', rating: 4.8, description: 'Baguette with garlic butter and herbs.', descriptionUz: 'Sarimsoqli saryog\' va ko\'katlar qo\'shilgan baget.', descriptionRu: 'Багет с чесночным маслом и травами.', specs: { 'Weight': '300g', 'Flavor': 'Garlic & Herb', 'Ready': 'To Heat' } },

    // Grains
    { id: 'gr1', name: 'Rice Laser (1kg)', nameUz: 'Lazer Guruch (1kg)', nameRu: 'Рис Лазер (1кг)', price: 22000, oldPrice: 25000, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.9, description: 'Premium Laser rice for perfect pilaf.', descriptionUz: 'Mukammal palov uchun premium Lazer guruch.', descriptionRu: 'Премиум рис Лазер для идеального плова.', specs: { 'Weight': '1 kg', 'Type': 'Laser', 'Origin': 'Xorazm' } },
    { id: 'gr2', name: 'Buckwheat (Grechka)', nameUz: 'Grechka', nameRu: 'Гречка', price: 14000, image: 'https://images.unsplash.com/photo-1590390886546-51203b860292?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.7, description: 'High quality roasted buckwheat kernels.', descriptionUz: 'Yuqori sifatli qovurilgan grechka donalari.', descriptionRu: 'Высококачественная жареная гречневая крупа.', specs: { 'Weight': '900g', 'Type': 'Roasted', 'Origin': 'Russia' } },
    { id: 'gr3', name: 'Pasta Spaghetti', nameUz: 'Spagetti', nameRu: 'Спагетти', price: 11000, image: 'https://images.unsplash.com/photo-1551462147-37885acc36f1?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.6, description: 'Durum wheat semolina spaghetti.', descriptionUz: 'Qattiq bug\'doy navidan tayyorlangan spagetti.', descriptionRu: 'Спагетти из твердых сортов пшеницы.', specs: { 'Weight': '500g', 'Type': 'Spaghetti', 'Cooking Time': '9 min' } },
    { id: 'gr4', name: 'Oats (Hercules)', nameUz: 'Gerkules', nameRu: 'Овсянка (Геркулес)', price: 9000, image: 'https://images.unsplash.com/photo-1584511652496-c65d63327d85?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.8, description: 'Rolled oats for healthy breakfast porridge.', descriptionUz: 'Foydali nonushta bo\'tqasi uchun suli yormasi.', descriptionRu: 'Овсяные хлопья для полезной каши на завтрак.', specs: { 'Weight': '400g', 'Type': 'Rolled', 'Cook': '5 min' } },
    { id: 'gr5', name: 'Red Lentils', nameUz: 'Qizil Yasmiq', nameRu: 'Красная Чечевица', price: 18000, image: 'https://images.unsplash.com/photo-1518970408542-a169b2b781b0?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.7, description: 'Quick cooking split red lentils.', descriptionUz: 'Tez pishadigan qizil yasmiq.', descriptionRu: 'Быстроразваривающаяся красная чечевица.', specs: { 'Weight': '800g', 'Type': 'Split Red', 'Use': 'Soups' } },
    { id: 'gr6', name: 'Chickpeas (Noxat)', nameUz: 'N ...noxat', nameRu: 'Нут (Горох)', price: 20000, image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.6, description: 'Large chickpeas for Hummus and Plov.', descriptionUz: 'Humm va Palov uchun yirik noxat.', descriptionRu: 'Крупный нут для хумуса и плова.', specs: { 'Weight': '1 kg', 'Size': 'Large', 'Origin': 'Uzbekistan' } },
    { id: 'gr7', name: 'Basmati Rice Premium', nameUz: 'Basmati Guruch Premium', nameRu: 'Рис Басмати Премиум', price: 35000, oldPrice: 40000, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 5.0, isNew: true, description: 'Extra long grain aromatic Basmati rice.', descriptionUz: 'Ekstra uzun donli xushbo\'y Basmati guruchi.', descriptionRu: 'Экстра длиннозерный ароматный рис Басмати.', specs: { 'Weight': '1 kg', 'Type': 'Basmati', 'Origin': 'Pakistan' } },
    { id: 'gr8', name: 'Wheat Flour (2kg)', nameUz: 'Bug\'doy Uni (2kg)', nameRu: 'Пшеничная Мука (2кг)', price: 15000, image: 'https://images.unsplash.com/photo-1622668516768-077ae1517c27?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.8, description: 'All-purpose white wheat flour.', descriptionUz: 'Oliy navli bug\'doy uni.', descriptionRu: 'Пшеничная мука высшего сорта.', specs: { 'Weight': '2 kg', 'Grade': 'Highest', 'Use': 'Baking' } },
    { id: 'gr9', name: 'Corn Flour', nameUz: 'Makkajo\'xori Uni', nameRu: 'Кукурузная Мука', price: 12000, image: 'https://images.unsplash.com/photo-1616738920141-86ae486bd291?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.5, description: 'Fine yellow corn flour.', descriptionUz: 'Mayda sariq makkajo\'xori uni.', descriptionRu: 'Тонкая желтая кукурузная мука.', specs: { 'Weight': '800g', 'Type': 'Corn', 'Gluten Free': 'Yes' } },
    { id: 'gr10', name: 'Barley', nameUz: 'Perlovka', nameRu: 'Перловка', price: 8000, image: 'https://images.unsplash.com/photo-1586554523971-d64cb207c425?auto=format&fit=crop&q=80&w=600', category: 'Grains', rating: 4.6, description: 'Pearl barley for soups and stews.', descriptionUz: 'Sho\'rva va garnirlar uchun marvarid arpa.', descriptionRu: 'Перловая крупа для супов и гарниров.', specs: { 'Weight': '900g', 'Type': 'Pearl', 'Cooking': '40 min' } },

    // Vegetables
    { id: 'vg1', name: 'Organic Tomatoes', nameUz: 'Organik Pomidorlar', nameRu: 'Органические Помидоры', price: 15000, image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.8, description: 'Sweet and juicy vine-ripened tomatoes.', descriptionUz: 'Shirin va sersuv pomidorlar.', descriptionRu: 'Сладкие и сочные помидоры.', specs: { 'Weight': '1 kg', 'Variety': 'Vine', 'Origin': 'Greenhouse' } },
    { id: 'vg2', name: 'Fresh Cucumbers', nameUz: 'Yangi Bodringlar', nameRu: 'Свежие Огурцы', price: 12000, image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.7, description: 'Crisp, short cucumbers ideal for salads.', descriptionUz: 'Qarsildoq, salatlar uchun ideal bodringlar.', descriptionRu: 'Хрустящие, короткие огурцы, идеальны для салатов.', specs: { 'Weight': '1 kg', 'Type': 'Short', 'Texture': 'Crunchy' } },
    { id: 'vg3', name: 'Potatoes', nameUz: 'Kartoshka', nameRu: 'Картофель', price: 6000, image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.6, description: 'Large potatoes suitable for frying or mashing.', descriptionUz: 'Qovurish yoki pyure qilish uchun katta kartoshkalar.', descriptionRu: 'Крупный картофель, подходит для жарки или пюре.', specs: { 'Weight': '1 kg', 'Variety': 'Yellow', 'Origin': 'Local' } },
    { id: 'vg4', name: 'Red Onions', nameUz: 'Qizil Piyoz', nameRu: 'Красный Лук', price: 5000, image: 'https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.5, description: 'Sweet red onions for salads and cooking.', descriptionUz: 'Salatlar va ovqatlar uchun shirin qizil piyoz.', descriptionRu: 'Сладкий красный лук для салатов и готовки.', specs: { 'Weight': '1 kg', 'Color': 'Red', 'Taste': 'Mild' } },
    { id: 'vg5', name: 'Carrots', nameUz: 'Sabzi', nameRu: 'Морковь', price: 4000, image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.7, description: 'Sweet and crunchy carrots, washed.', descriptionUz: 'Shirin va qarsildoq sabzi, yuvilgan.', descriptionRu: 'Сладкая и хрустящая морковь, мытая.', specs: { 'Weight': '1 kg', 'Washed': 'Yes', 'Origin': 'Zarafshan' } },
    { id: 'vg6', name: 'Bell Peppers Mix', nameUz: 'Bulg\'or Qalampiri Miks', nameRu: 'Смесь Болгарских Перцев', price: 25000, oldPrice: 30000, image: 'https://images.unsplash.com/photo-1563565375-f3fdf5efe269?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.9, description: 'Mix of red, yellow, and green bell peppers.', descriptionUz: 'Qizil, sariq va yashil bulg\'or qalampirlari aralashmasi.', descriptionRu: 'Смесь красного, желтого и зеленого перцев.', specs: { 'Weight': '1 kg', 'Colors': 'Mixed', 'Taste': 'Sweet' } },
    { id: 'vg7', name: 'Broccoli', nameUz: 'Brokkoli', nameRu: 'Брокколи', price: 18000, image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.8, isNew: true, description: 'Fresh green broccoli heads.', descriptionUz: 'Yangi yashil brokkoli.', descriptionRu: 'Свежая зеленая брокколи.', specs: { 'Weight': '1 kg', 'Freshness': 'Daily', 'Origin': 'Local' } },
    { id: 'vg8', name: 'Garlic Pack', nameUz: 'Sarimsoq Piyoz (To\'plam)', nameRu: 'Чеснок (Упаковка)', price: 3000, image: 'https://images.unsplash.com/photo-1615477093268-b80c2aec3c73?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.9, description: 'Aromatic garlic bulbs mesh pack.', descriptionUz: 'Xushbo\'y sarimsoq piyoz.', descriptionRu: 'Ароматный чеснок в сетке.', specs: { 'Count': '3 bulbs', 'Origin': 'China', 'Shelf Life': '3 months' } },
    { id: 'vg9', name: 'Fresh Spinach', nameUz: 'Yangi Ismaloq', nameRu: 'Свежий Шпинат', price: 8000, image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.8, description: 'Young spinach leaves, washed and ready to eat.', descriptionUz: 'Yosh ismaloq barglari, yuvilgan va iste\'molga tayyor.', descriptionRu: 'Молодые листья шпината, мытые и готовые к употреблению.', specs: { 'Weight': '200g', 'Pack': 'Bag', 'Washed': 'Yes' } },
    { id: 'vg10', name: 'Eggplant', nameUz: 'Baqlajon', nameRu: 'Баклажан', price: 10000, image: 'https://images.unsplash.com/photo-1615485925694-a0397ae0344d?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.6, description: 'Glossy purple eggplants.', descriptionUz: 'Yaltiroq binafsharang baqlajonlar.', descriptionRu: 'Глянцевые фиолетовые баклажаны.', specs: { 'Weight': '1 kg', 'Shape': 'Long', 'Origin': 'Greenhouse' } },
    { id: 'vg11', name: 'Zucchini', nameUz: 'Qovoqcha (Kabachki)', nameRu: 'Кабачки', price: 7000, image: 'https://images.unsplash.com/photo-1596350389363-22f3068e4c76?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.7, description: 'Fresh green zucchini squash.', descriptionUz: 'Yangi yashil qovoqchalar.', descriptionRu: 'Свежие зеленые кабачки.', specs: { 'Weight': '1 kg', 'Skin': 'Thin', 'Origin': 'Local' } },
    { id: 'vg12', name: 'Cauliflower', nameUz: 'Gulkaram', nameRu: 'Цветная Капуста', price: 15000, image: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3d54?auto=format&fit=crop&q=80&w=600', category: 'Vegetables', rating: 4.8, description: 'Dense white cauliflower heads.', descriptionUz: 'Zich oq gulkaram boshlari.', descriptionRu: 'Плотные кочаны цветной капусты.', specs: { 'Unit': '1 head', 'Approx Wt': '800g', 'Freshness': 'High' } },

    // Fruits
    { id: 'fr1', name: 'Fresh Bananas', nameUz: 'Banani', nameRu: 'Свежие Бананы', price: 15000, image: 'https://images.unsplash.com/photo-1571771894821-ad9958a3f747?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.8, description: 'Sweet and ripe yellow bananas.', descriptionUz: 'Shirin va yetilgan sariq bananlar.', descriptionRu: 'Сладкие и спелые желтые бананы.', specs: { 'Weight': '1 kg', 'Origin': 'Ecuador', 'Ripeness': 'Yellow' } },
    { id: 'fr2', name: 'Red Apples', nameUz: 'Qizil Olmalar', nameRu: 'Красные Яблоки', price: 12000, image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.7, description: 'Crisp and sweet red apples.', descriptionUz: 'Qarsildoq va shirin qizil olmalar.', descriptionRu: 'Хрустящие и сладкие красные яблоки.', specs: { 'Weight': '1 kg', 'Variety': 'Fuji', 'Origin': 'Poland' } },
    { id: 'fr3', name: 'Green Grapes', nameUz: 'Yashil Uzum', nameRu: 'Зеленый Виноград', price: 25000, image: 'https://images.unsplash.com/photo-1537640538966-79f369b41f8f?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.9, description: 'Seedless sweet green grapes.', descriptionUz: 'Urug\'siz shirin yashil uzum.', descriptionRu: 'Бессемянный сладкий зеленый виноград.', specs: { 'Weight': '1 kg', 'Seedless': 'Yes', 'Variety': 'Kish-Mish' } },
    { id: 'fr4', name: 'Juicy Oranges', nameUz: 'Sersuv Apelsinlar', nameRu: 'Сочные Апельсины', price: 20000, image: 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.6, description: 'Fresh sun-ripened oranges.', descriptionUz: 'Quyoshda yetilgan yangi apelsinlar.', descriptionRu: 'Свежие, созревшие на солнце апельсины.', specs: { 'Weight': '1 kg', 'Taste': 'Sweet-Sour', 'Origin': 'Turkey' } },
    { id: 'fr5', name: 'Strawberries Fresh', nameUz: 'Yangi Qulupnay', nameRu: 'Свежая Клубника', price: 45000, image: 'https://images.unsplash.com/photo-1464965911861-746a04b4b032?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 5.0, isNew: true, description: 'Sweet seasonal strawberries.', descriptionUz: 'Shirin mavsumiy qulupnay.', descriptionRu: 'Сладкая сезонная клубника.', specs: { 'Weight': '500g', 'Pack': 'Punnet', 'Season': 'Summer' } },
    { id: 'fr6', name: 'Watermelon', nameUz: 'Tarvuz', nameRu: 'Арбуз', price: 30000, image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.9, description: 'Sweet and refreshing whole watermelon.', descriptionUz: 'Shirin va chanqoq bosdi tarvuz.', descriptionRu: 'Сладкий и освежающий арбуз.', specs: { 'Unit': '1 pc', 'Approx Wt': '5-7 kg', 'Origin': 'Local' } },
    { id: 'fr7', name: 'Lemon', nameUz: 'Limon', nameRu: 'Лимон', price: 18000, image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.7, description: 'Zesty yellow lemons.', descriptionUz: 'O\'tkir ta\'mli sariq limonlar.', descriptionRu: 'Пикантные желтые лимоны.', specs: { 'Weight': '1 kg', 'Use': 'Tea/Cooking', 'Origin': 'Turkey' } },
    { id: 'fr8', name: 'Kiwi Pack', nameUz: 'Kivi (To\'plam)', nameRu: 'Киви (Упаковка)', price: 35000, image: 'https://images.unsplash.com/photo-1585059895524-72359e06138a?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.8, description: 'Fuzzy kiwi fruit rich in vitamins.', descriptionUz: 'Vitaminlarga boy tukli kivi mevasi.', descriptionRu: 'Пушистый киви, богатый витаминами.', specs: { 'Weight': '1 kg', 'Origin': 'Iran', 'Taste': 'Sweet-Tart' } },
    { id: 'fr9', name: 'Pomegranate', nameUz: 'Anor', nameRu: 'Гранат', price: 28000, image: 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 4.9, description: 'Deep red pomegranates with juicy seeds.', descriptionUz: 'Sersuv donali to\'q qizil anorlar.', descriptionRu: 'Темно-красные гранаты с сочными зернами.', specs: { 'Weight': '1 kg', 'Variety': 'Qizil', 'Origin': 'Surxondaryo' } },
    { id: 'fr10', name: 'Avocado Ripe', nameUz: 'Avokado', nameRu: 'Авокадо', price: 25000, image: 'https://images.unsplash.com/photo-1523049673856-428689c8ae64?auto=format&fit=crop&q=80&w=600', category: 'Fruits', rating: 5.0, description: 'Creamy Haas avocado ready to eat.', descriptionUz: 'Iste\'molga tayyor qaymoqli Haas avokadosi.', descriptionRu: 'Сливочное авокадо Хаас, готовое к употреблению.', specs: { 'Unit': '1 pc', 'Ripeness': 'Ready', 'Origin': 'Kenya/Peru' } },
];

export const news: News[] = [
    {
        id: '1',
        title: 'Yangi iPhone 15 endi sotuvda!',
        excerpt: 'Lider Bazar do\'konlarida yangi iPhone 15 modellari eng yaxshi narxlarda.',
        date: '2024-01-20',
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
        badge: 'New Arrival',
        badgeColor: '#fbbf24', // Amber/Gold
    },
    {
        id: '2',
        title: 'Katta chegirmalar boshlandi',
        excerpt: 'Barcha maishiy texnikalar uchun 20% gacha chegirmalar.',
        date: '2024-01-18',
        image: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?auto=format&fit=crop&q=80&w=800',
        badge: 'Big Sale',
        badgeColor: '#ef4444', // Red
    },
];
